# services:
#   backend:
#     build:
#       args:
#         - user=docker-user
#           uid:1000
#       context: ./
#       dockerfile: docker/php/Dockerfile
#     container_name: laravel_app
#     working_dir: /var/www/html
#     ports:
#       - "9000:9000"
#     volumes:
#       - ./backend:/var/www/html
#     depends_on:
#       - mysql
#     networks:
#       - laravel

#   frontend:
#     image: node:22
#     container_name: laravel_frontend
#     working_dir: /app
#     volumes:
#       - ./frontend:/app
#     command: npm run serve
#     ports:
#       - "3000:3000"
#     networks:
#       - laravel

#   nginx:
#     image: nginx:latest
#     container_name: laravel_nginx
#     ports:
#       - "8080:80"
#     volumes:
#       - ./:/var/www/html
#       - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
#     depends_on:
#       - frontend
#       - backend
#     networks:
#       - laravel

#   mysql:
#     image: mysql:8.0
#     container_name: laravel_mysql
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_DATABASE: laravel
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_USER: laravel
#       MYSQL_PASSWORD: secret
#     volumes:
#       - ./docker/mysql_data:/var/lib/mysql
#     networks:
#       - laravel

# volumes:
#   mysql_data:

# networks:
#   laravel:
#     driver: bridge

services:
  atc-backend:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
      args:
        - user=docker-user
        - uid=1000
    container_name: laravel_appE
    working_dir: /var/www/html
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - atc-mysql
    networks:
      - atc-laravel

  atc-frontend:
    image: node:22
    container_name: laravel_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: npm run serve
    ports:
      - "3000:3000"
    networks:
      - atc-laravel

  atc-nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - atc-frontend
      - atc-backend
    networks:
      - atc-laravel

  atc-mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - ./docker/mysql_data:/var/lib/mysql
    networks:
      - atc-laravel

networks:
  atc-laravel:
    driver: bridge
